replicas: 3
auditInterval: 86400                                                           #ABS Custom Default 60 sec #auditInterval=0 to disable
auditMatchKindOnly: false
constraintViolationsLimit: 1000                                                 #ABS Custom Default 20
auditFromCache: false
disableMutation: false
disableValidatingWebhook: $DISABLE_VALIDATING_WEBHOOK                           #ABS Custom Default false
validatingWebhookTimeoutSeconds: 3
validatingWebhookFailurePolicy: Ignore
validatingWebhookCheckIgnoreFailurePolicy: Fail
enableDeleteOperations: false
enableExternalData: false
mutatingWebhookFailurePolicy: Ignore
mutatingWebhookTimeoutSeconds: 3
auditChunkSize: 500
logLevel: INFO
logDenies: true                                                                 #ABS Custom Default false
emitAdmissionEvents: false
emitAuditEvents: false
resourceQuota: true
postInstall:
  labelNamespace:
    enabled: true
    image:
      repository: escoacrprod01.azurecr.io/esco/openpolicyagent/gatekeeper-crds #ABS Custom Default openpolicyagent/gatekeeper-crds
      tag: $OPA_VERSION                                                         #ABS Custom Default v3.9.0
      pullPolicy: IfNotPresent
      pullSecrets: []
image:
  repository: escoacrprod01.azurecr.io/esco/openpolicyagent/gatekeeper          #ABS Custom Default openpolicyagent/gatekeeper
  crdRepository: openpolicyagent/gatekeeper-crds
  release: $OPA_VERSION                                                         #ABS Custom Default v3.9.0
  pullPolicy: IfNotPresent
  pullSecrets: []
podAnnotations:
  { container.seccomp.security.alpha.kubernetes.io/manager: runtime/default }
podLabels: {}
podCountLimit: 100
secretAnnotations: {}
controllerManager:
  exemptNamespaces: []
  exemptNamespacePrefixes: []
  hostNetwork: false
  dnsPolicy: Default
  port: 8443
  metricsPort: 8888
  healthPort: 9090
  priorityClassName: system-cluster-critical
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: gatekeeper.sh/operation
                  operator: In
                  values:
                    - webhook
            topologyKey: kubernetes.io/hostname
          weight: 100
  tolerations: []
  nodeSelector: { kubernetes.io/os: linux }
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
audit:
  hostNetwork: false
  dnsPolicy: Default
  metricsPort: 8888
  healthPort: 9090
  priorityClassName: system-cluster-critical
  affinity: {}
  tolerations: []
  nodeSelector: { kubernetes.io/os: linux }
  writeToRAMDisk: false
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
crds:
  resources: {}
pdb:
  controllerManager:
    minAvailable: 1
service: {}
disabledBuiltins:
psp:
  enabled: true
upgradeCRDs:
  enabled: true
rbac:
  create: true
